image: python:2.7

test:
  script:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - echo $VCD_HOST
  - echo $VCD_USERNAME
  - echo $VCD_PASSWORD
  - nosetests --tc-format yaml --tc-file tests/config.yaml
    --tc=vcloud.host:$VCD_HOST
    --tc=vcloud.username:$VCD_USERNAME
    --tc=vcloud.password:$VCD_PASSWORD
    tests/00010_vcd_login.py
  - cat $TMPDIR/pyvcloud.log
