sudo: required

services:
  - docker

python:
  - '2.7'

env:
  matrix:
  - TOX_ENV=flake8

install:
  - python setup.py install
  - pip install -r test-requirements.txt

script:
  - pip list --format=columns
